import { Roboto } from "next/font/google";
import "../styles/globals.css";
import Navigation from "../components/Navigation/Navigation";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="bg-blue-50 h-screen w-screen">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
