import { Roboto } from "next/font/google";
import "../styles/globals.css";
import Navigation from "../components/Navigation/Navigation";
import { GlobalProvider } from "@/context/globalContext";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="bg-gray-50 h-screen w-screen">
          <GlobalProvider>
            <Navigation />
            {children}
          </GlobalProvider>
        </div>
      </body>
    </html>
  );
}
